def _bullets(items):

    return "\n".join(f"- {item}" for item in items if item)


def _steps(items):

    return "\n".join(f"{index}. {item}" for index, item in enumerate(items, start=1) if item)


def _field_block(label, value):

    if not value:
        return ""
    if isinstance(value, (list, tuple)):
        value = _bullets(value)
    return f"{label}:\n{value}"


def _record(
    key,
    service_name,
    category,
    intent_keywords,
    purpose,
    official_url,
    eligibility="",
    who_can_use="",
    prerequisites=None,
    documents=None,
    dsp_navigation=None,
    form_filling=None,
    validation_rules=None,
    upload_requirements=None,
    workflow=None,
    status_tracking="",
    approval_process="",
    download_print="",
    common_errors=None,
    comparison=None,
    important_notes=None,
    official_helpdesk="",
    official_tracking_url="",
    faq=None,
):

    return {
        "key": key,
        "service_name": service_name,
        "category": category,
        "intent_keywords": tuple(intent_keywords),
        "purpose": purpose,
        "who_can_use": who_can_use,
        "eligibility": eligibility,
        "prerequisites": tuple(prerequisites or ()),
        "documents": tuple(documents or ()),
        "dsp_navigation": tuple(dsp_navigation or ()),
        "form_filling": tuple(form_filling or ()),
        "validation_rules": tuple(validation_rules or ()),
        "upload_requirements": tuple(upload_requirements or ()),
        "workflow": tuple(workflow or ()),
        "status_tracking": status_tracking,
        "approval_process": approval_process,
        "download_print": download_print,
        "common_errors": tuple(common_errors or ()),
        "comparison": tuple(comparison or ()),
        "important_notes": tuple(important_notes or ()),
        "official_url": official_url,
        "official_helpdesk": official_helpdesk,
        "official_tracking_url": official_tracking_url,
        "faq": tuple(faq or ()),
    }


def _context(record):

    lines = [
        f"Source: {record['official_url']}",
        f"Service/form: {record['service_name']}",
        _field_block("Purpose", record["purpose"]),
        _field_block("Who Can Use", record["who_can_use"]),
        _field_block("Eligibility", record["eligibility"]),
        _field_block("Prerequisites", record["prerequisites"]),
        _field_block("Required Documents", record["documents"]),
        _field_block("DSP Navigation", _steps(record["dsp_navigation"])),
        _field_block("Form Filling Guide", _steps(record["form_filling"])),
        _field_block("Common Validation Rules", record["validation_rules"]),
        _field_block("Upload Requirements", record["upload_requirements"]),
        _field_block("Application Workflow", _steps(record["workflow"])),
        _field_block("Status Tracking", record["status_tracking"]),
        _field_block("Approval Process", record["approval_process"]),
        _field_block("Download / Print", record["download_print"]),
        _field_block("Common Errors", record["common_errors"]),
        _field_block("Comparison", record["comparison"]),
        _field_block("Important Notes", record["important_notes"]),
        _field_block("Official URL", record["official_url"]),
        _field_block("Official Helpdesk", record["official_helpdesk"]),
        _field_block("Official Tracking Page", record["official_tracking_url"]),
        _field_block("FAQ", record["faq"]),
        "DPDP note: Do not paste Aadhaar, PAN, bank details, OTP, passwords, health data, or child/minor personal data in this chat. Enter those only inside the official CSC/service portal.",
    ]

    return "\n".join(line for line in lines if line)


def _certificate_record(key, service_name, keywords, event_label, documents):

    return _record(
        key=key,
        service_name=service_name,
        category="Certificates",
        intent_keywords=keywords,
        purpose=f"Help citizens apply for or track {service_name.lower()} through the enabled CSC/Digital Seva or official state e-District service.",
        official_url="https://services.india.gov.in/",
        who_can_use="Citizen/applicant or authorized CSC/VLE role where the certificate service is enabled for the state/district.",
        eligibility="Eligibility depends on state rules, local authority rules, and the exact certificate type.",
        prerequisites=(
            "Citizen consent before filling personal/family details.",
            "Correct state, district, tehsil/block, village/ward, and local authority details.",
            "Original documents ready for verification.",
        ),
        documents=documents,
        dsp_navigation=(
            "Login to Digital Seva Portal with authorized CSC/VLE credentials.",
            "Search for the state e-District/certificate service or open the official state service page if redirected.",
            f"Select {service_name} or the closest official certificate option shown for the state.",
            "Read fee, document, declaration, and role access instructions before entry.",
        ),
        form_filling=(
            "Choose state/district and exact certificate type.",
            "Fill applicant name, parent/spouse details, mobile, address, category/location, and purpose as per documents.",
            f"Fill {event_label} details exactly as shown in official proof or local records.",
            "Upload only documents asked by the portal in allowed format and size.",
            "Review spelling, dates, relationship, location, declaration, and uploaded files before submit.",
        ),
        validation_rules=(
            "Applicant details must match proof documents.",
            "Dates, district, tehsil/block, village/ward, and relationship fields must be correct.",
            "Mandatory declarations must be accepted only after explaining them to the citizen.",
        ),
        upload_requirements=(
            "Upload clear scans/photos only when the portal asks.",
            "Use the file type and size shown on the official portal.",
        ),
        workflow=(
            "Fill certificate form.",
            "Upload documents.",
            "Pay official fee if shown.",
            "Submit application and save acknowledgement/reference number.",
            "Department/local authority verifies and approves or rejects as per rules.",
        ),
        status_tracking="Track using the application/reference number in the same CSC/state e-District service or official status option.",
        approval_process="Approval depends on local authority verification, document check, and state workflow.",
        download_print="After approval, download/print certificate only from the official portal option.",
        common_errors=(
            "Wrong state/district/service selected. Resolution: restart with the correct state service.",
            "Document mismatch. Resolution: upload proof matching applicant and certificate details.",
            "Application pending. Resolution: track with reference number and follow official department/helpdesk process.",
        ),
        important_notes=(
            "Certificate rules vary by state. Treat portal instructions as final.",
            "Do not promise approval or timeline unless the official portal shows it.",
        ),
        faq=(
            "Can one guide cover every state? No. Use this as safe CSC workflow guidance and verify state-specific fields inside the official portal.",
            "What should be saved after submit? Application/reference number, acknowledgement, receipt, and status page details.",
        ),
    )


COMMON_DSP_ERROR_ITEMS = (
    "Service not visible. Cause: role, state, or service access is not enabled. Resolution: check Digital Seva service availability/authorization.",
    "Mandatory field missing. Cause: required field left blank. Resolution: complete all marked fields before submit.",
    "Document upload failed. Cause: wrong file type/size or unclear scan. Resolution: upload clear file in portal allowed format.",
    "Payment pending/failed. Cause: bank/payment gateway response pending. Resolution: check status before trying duplicate payment.",
)


CORE_SERVICE_RECORDS = (
    _record(
        key="csc_overview",
        service_name="CSC / Digital Seva Portal / VLE Overview",
        category="CSC Foundation",
        intent_keywords=("csc", "common service centre", "digital seva portal", "vle", "what is csc", "what is digital seva", "what is vle", "सीएससी", "डिजिटल सेवा", "वीएलई"),
        purpose="Common Service Centres help deliver digital, government, financial, education, health, agriculture, travel, insurance, and citizen services through authorized Village Level Entrepreneurs.",
        official_url="https://csc.gov.in/",
        who_can_use="Citizens can use CSC services through a nearby CSC/VLE. VLEs use Digital Seva Portal after official registration and authorization.",
        eligibility="VLE access and service availability depend on CSC registration, approval, role, state, and service provider authorization.",
        prerequisites=("Official CSC/Digital Seva account for VLE services.", "Citizen consent and required documents for each service.", "Use only CSC or official service portals."),
        documents=("Documents depend on the selected service.", "For VLE registration, use the official CSC registration portal requirements."),
        dsp_navigation=("Open Digital Seva Portal.", "Login with authorized CSC/VLE credentials.", "Search or select the required service category.", "Open the exact service and follow its official form instructions."),
        form_filling=("Identify the exact citizen service first.", "Keep required documents ready.", "Fill details exactly as per proof documents.", "Upload only required documents.", "Save acknowledgement, receipt, or reference number."),
        workflow=("Citizen requests service.", "VLE verifies official service availability.", "Form is filled on official portal.", "Payment/verification is completed if required.", "Acknowledgement/status/certificate/receipt is shared."),
        status_tracking="Use the same Digital Seva service, official department portal, receipt number, or acknowledgement number.",
        common_errors=COMMON_DSP_ERROR_ITEMS,
        important_notes=("The assistant gives strong guidance for priority CSC services and safe general guidance for other Digital Seva services.", "Exact fee, eligibility, and field names must be verified on the official portal screen."),
        faq=("What is a VLE? A Village Level Entrepreneur who operates CSC services after official approval.", "What is DSP? Digital Seva Portal is the CSC service access portal for authorized users."),
    ),
    _record(
        key="vle_registration",
        service_name="VLE Registration / CSC Registration",
        category="CSC Foundation",
        intent_keywords=("vle registration", "become vle", "csc registration", "new csc id", "register csc", "वीएलई रजिस्ट्रेशन", "सीएससी रजिस्ट्रेशन"),
        purpose="Help an applicant start CSC/VLE registration through the official CSC registration portal.",
        official_url="https://register.csc.gov.in/",
        who_can_use="Applicants who want to become CSC Village Level Entrepreneurs and meet the portal requirements.",
        eligibility="Eligibility, certificate requirements, and approval depend on the official CSC registration portal and current CSC policy.",
        prerequisites=("Active mobile/email.", "TEC or other certificate details if the portal asks.", "Correct applicant, bank, and centre/location details."),
        documents=("Applicant identity proof as requested by portal.", "PAN and bank details if asked.", "Photo and address/centre proof if asked.", "Certificates such as TEC/IIBF only if the portal requires them."),
        dsp_navigation=("Open the official CSC registration portal.", "Choose the VLE/new registration option shown on the portal.", "Select application type and enter required registration/certificate/mobile details.", "Complete OTP/eKYC or verification only on the official portal."),
        form_filling=("Select correct application type.", "Enter certificate number, mobile, email, and captcha as shown.", "Fill personal, address, bank, and centre details carefully.", "Upload only documents requested by the portal.", "Submit and save reference/application number."),
        validation_rules=("Mobile/email OTP must be entered only on official portal.", "Certificate/application type must match the applicant.", "Bank and applicant details should be correct before submission."),
        workflow=("Register or start application.", "Complete authentication/eKYC if asked.", "Fill details and upload documents.", "Submit for verification.", "Wait for CSC approval/communication."),
        status_tracking="Use application/reference number on the official registration/status option.",
        approval_process="CSC verifies application details and approves/rejects as per official registration policy.",
        common_errors=COMMON_DSP_ERROR_ITEMS + ("Invalid certificate/application type. Resolution: verify certificate number and application type on the official portal.",),
        official_tracking_url="https://register.csc.gov.in/",
        faq=("Can approval be guaranteed? No. Approval depends on CSC verification.", "Where should OTP/Aadhaar be entered? Only on the official registration portal."),
    ),
    _record(
        key="pm_kisan",
        service_name="PM-KISAN",
        category="Agriculture",
        intent_keywords=("pm kisan", "pm-kisan", "pmkisan", "farmer registration", "pm kisan status", "farmer status", "पीएम किसान", "किसान सम्मान निधि"),
        purpose="PM-KISAN is an official farmer benefit scheme service where farmers can check status and use farmer-facing services on the official PM-KISAN portal.",
        official_url="https://pmkisan.gov.in/",
        who_can_use="Farmers/applicants and authorized CSC/VLE assistance where PM-KISAN service is available.",
        eligibility="Eligibility must be checked on the official PM-KISAN portal, mobile app, or official status/KYS option.",
        prerequisites=("Farmer consent.", "Correct farmer and land/account details if the official portal asks.", "Aadhaar/eKYC only inside the official PM-KISAN flow."),
        documents=("Identity/farmer details as requested by official portal.", "Land/account details if required by the service.", "Mobile linked/OTP access if official flow requires it."),
        dsp_navigation=("Login to Digital Seva Portal if PM-KISAN service is enabled, or open PM-KISAN official portal.", "Select farmer registration, eKYC, beneficiary status, or Know Your Status option as needed.", "Enter details only on the official PM-KISAN screen.", "Save acknowledgement/status details."),
        form_filling=("Choose the exact PM-KISAN service.", "Enter farmer details exactly as per official records.", "Complete eKYC/OTP only on official portal if required.", "Review land/bank/status details shown by the portal.", "Submit and save reference/status."),
        validation_rules=("Farmer details must match official records.", "Do not change eligibility manually.", "Aadhaar/OTP must not be shared in chat."),
        workflow=("Search/register/update as per selected PM-KISAN option.", "Complete verification/eKYC if required.", "Submit and save reference/status.", "Track status on PM-KISAN portal."),
        status_tracking="Use Know Your Status/beneficiary status options on pmkisan.gov.in or official PM-KISAN app.",
        common_errors=("Beneficiary not found. Resolution: recheck official search details.", "eKYC pending/failed. Resolution: complete eKYC only through official PM-KISAN flow.", "Status pending/rejected. Resolution: follow official status message and department process."),
        important_notes=("Use only pmkisan.gov.in for PM-KISAN status or services.",),
        official_tracking_url="https://pmkisan.gov.in/",
        faq=("Can the assistant confirm eligibility? No. Eligibility must be checked on PM-KISAN official status/KYS.",),
    ),
    _record(
        key="kisan_credit_card",
        service_name="Kisan Credit Card (KCC)",
        category="Agriculture",
        intent_keywords=("kisan credit card", "kcc", "kcc apply", "kcc status", "किसान क्रेडिट कार्ड"),
        purpose="KCC helps farmers access credit for agriculture and allied needs through banks/official scheme channels.",
        official_url="https://services.india.gov.in/",
        who_can_use="Farmers or allied activity applicants as per bank/government scheme rules.",
        eligibility="Eligibility depends on the bank, crop/allied activity, land/occupation proof, and official scheme rules.",
        prerequisites=("Farmer consent.", "Bank branch/scheme requirements.", "Land/crop/allied activity details ready."),
        documents=("Identity proof.", "Address proof.", "Land/crop or allied activity proof if required.", "Bank account/details as required by official channel.", "Photograph if required."),
        dsp_navigation=("Login to DSP if KCC/agriculture loan service is enabled, or use official bank/government service channel.", "Search Kisan Credit Card/KCC service.", "Read bank/scheme instructions before filling.", "Continue on official bank/government page if redirected."),
        form_filling=("Select KCC/agriculture credit service.", "Fill farmer name, address, mobile, village, land/crop or allied activity details.", "Enter bank/account details only on official form if required.", "Upload documents requested by bank/portal.", "Submit and save acknowledgement."),
        workflow=("Fill application.", "Bank/authority verifies documents and eligibility.", "Credit assessment/approval is completed by bank.", "KCC/account/card or loan facility is issued as per bank process."),
        status_tracking="Track through bank branch, official service status, or acknowledgement number if provided.",
        common_errors=COMMON_DSP_ERROR_ITEMS + ("Land/crop details mismatch. Resolution: verify records before submit.",),
        important_notes=("Loan approval and limits are decided by the bank/official scheme process, not by CSC assistant.",),
    ),
    _record(
        key="telemedicine",
        service_name="Telemedicine / Doctor Consultation",
        category="Health",
        intent_keywords=("telemedicine", "doctor consultation", "health consultation", "jiva telemedicine", "super speciality consultation", "टेलीमेडिसिन", "डॉक्टर सलाह"),
        purpose="Help citizens book or use telemedicine/doctor consultation services available through CSC health service channels.",
        official_url="https://cschealth.in/",
        who_can_use="Citizens/patients assisted by authorized CSC/VLE or official health service role.",
        eligibility="Service availability, doctor type, fee, and appointment options depend on the official CSC health/telemedicine portal.",
        prerequisites=("Patient consent.", "Basic patient details.", "Symptoms/reports/prescription only inside official health portal.", "Payment method if consultation fee is shown."),
        documents=("ID/contact details if the portal asks.", "Previous prescription or report only if needed.", "Referral details if required."),
        dsp_navigation=("Login to DSP if the health service is enabled, or open official CSC health service portal.", "Select Telemedicine/Consultation/Doctor service.", "Choose doctor/speciality/date/time as shown.", "Continue appointment/payment on official screen."),
        form_filling=("Fill patient name, age, gender, contact, and location as required.", "Enter symptoms and health details only on official health screen.", "Upload report/prescription only if asked.", "Confirm doctor, time, fee, and consent before submit.", "Save consultation ID/receipt."),
        workflow=("Create appointment/consultation request.", "Pay fee if applicable.", "Consult doctor through official channel.", "Save prescription/advice/consultation reference."),
        status_tracking="Use appointment ID/consultation reference in the official health portal or helpdesk flow.",
        download_print="Download/print prescription, receipt, or consultation summary if the portal provides it.",
        common_errors=("Appointment slot not available. Resolution: choose another slot/doctor.", "Payment pending. Resolution: check receipt/status before retry.", "Report upload failed. Resolution: use allowed file type and clear scan."),
        important_notes=("Health information is sensitive. Do not type symptoms with personal identifiers in chat.",),
    ),
    _record(
        key="new_pan",
        service_name="New PAN Application",
        category="PAN Services",
        intent_keywords=("new pan", "apply pan", "new pan registration", "pan card apply", "pan application", "नया पैन", "पैन आवेदन"),
        purpose="Help applicants apply for a new PAN through official PAN service portals available to the user/CSC.",
        official_url="https://www.protean-tinpan.com/services/pan/pan-index.html",
        who_can_use="Applicant or authorized assistance role using official PAN service portal.",
        eligibility="Use the correct applicant category and official PAN application form as shown by the portal.",
        prerequisites=("Applicant consent.", "Correct applicant category.", "Identity, address, and date-of-birth proof ready.", "Photo/signature if portal asks."),
        documents=("Proof of identity.", "Proof of address.", "Proof of date of birth.", "Photo/signature if required by selected mode."),
        dsp_navigation=("Login to DSP if PAN service is enabled, or open official PAN service portal.", "Select New PAN/Application service.", "Select applicant category and form type shown by official portal.", "Continue only on official PAN screen."),
        form_filling=("Choose New PAN service.", "Fill name exactly as per proof documents.", "Fill date of birth/incorporation, gender/category, parent name, address, mobile/email as required.", "Enter Aadhaar/PAN/OTP only inside official portal fields if asked.", "Upload/submit proof documents, photo/signature/declaration as required.", "Pay fee only on official PAN portal and save acknowledgement."),
        validation_rules=("Name, DOB, address, and applicant category must match documents.", "Form 49A/49AA selection must follow official portal instructions.", "Do not paste PAN/Aadhaar/OTP in chat."),
        workflow=("Fill new PAN form.", "Upload/submit documents.", "Pay official fee.", "Submit and save acknowledgement number.", "Track on official PAN portal."),
        status_tracking="Track using acknowledgement/coupon/reference number on the official PAN portal.",
        common_errors=("Name mismatch. Resolution: enter name exactly as proof document.", "Wrong category/form type. Resolution: verify applicant category before submit.", "Payment/acknowledgement missing. Resolution: check official PAN portal status."),
        official_tracking_url="https://www.protean-tinpan.com/services/pan/pan-index.html",
        faq=("What is most important? Exact name/DOB/address match with proof documents.",),
    ),
    _record(
        key="pan_correction",
        service_name="PAN Correction / Change Request",
        category="PAN Services",
        intent_keywords=("pan correction", "correct pan", "name correction", "dob correction", "pan change", "पैन सुधार", "नाम सुधार", "जन्मतिथि सुधार"),
        purpose="Help applicants correct or update PAN data through official PAN correction/change request service.",
        official_url="https://www.protean-tinpan.com/services/pan/pan-index.html",
        who_can_use="PAN holder or authorized assistance role with citizen consent.",
        eligibility="Use correction/change request only for changes supported by the official PAN portal.",
        prerequisites=("Existing PAN details.", "Proof for the requested correction.", "Applicant consent and declaration."),
        documents=("Existing PAN proof if required.", "Proof supporting name/DOB/address or other correction.", "Identity/address/DOB proof as required by official portal."),
        dsp_navigation=("Open PAN service through DSP if enabled or official PAN portal.", "Select correction/change request.", "Enter existing PAN/application details only on official portal.", "Proceed with document upload/payment if required."),
        form_filling=("Select fields that need correction only.", "Enter corrected details exactly as proof document.", "Upload proof for each correction requested.", "Review old and new details before submit.", "Pay fee if shown and save acknowledgement."),
        validation_rules=("Only request corrections supported by official portal.", "Correction proof must match the new detail.", "Existing PAN must be entered only on official PAN portal."),
        workflow=("Fill correction request.", "Upload supporting proof.", "Pay fee if applicable.", "Submit and save acknowledgement.", "Track correction status."),
        status_tracking="Track with acknowledgement/reference number on official PAN portal.",
        common_errors=("Correction proof mismatch. Resolution: upload correct supporting proof.", "Wrong field selected. Resolution: select only fields needing correction.", "Existing PAN details mismatch. Resolution: verify PAN holder records before submit."),
        official_tracking_url="https://www.protean-tinpan.com/services/pan/pan-index.html",
    ),
    _record(
        key="pan_reprint",
        service_name="PAN Reprint / Duplicate PAN Card",
        category="PAN Services",
        intent_keywords=("pan reprint", "duplicate pan", "lost pan", "pan lost", "reissue pan", "पैन रीप्रिंट", "डुप्लीकेट पैन"),
        purpose="Help PAN holders request reprint/reissue of PAN card through official PAN portal where the PAN data is already available.",
        official_url="https://www.protean-tinpan.com/services/pan/pan-index.html",
        who_can_use="Existing PAN holder or authorized assistance role with citizen consent.",
        eligibility="Use reprint/reissue only when the applicant already has a PAN and the official portal allows reprint.",
        prerequisites=("Existing PAN details.", "Correct mobile/email/address flow as required by official portal.", "Payment method if fee is shown."),
        documents=("Existing PAN details.", "Identity/contact verification if official portal asks.", "Address proof only if reprint flow asks."),
        dsp_navigation=("Open PAN service through DSP if enabled or official PAN portal.", "Select reprint/reissue/duplicate PAN option.", "Enter existing PAN details only on official portal.", "Complete OTP/payment and save acknowledgement."),
        form_filling=("Select PAN reprint/reissue service.", "Enter existing PAN and required identity/date/contact details on official portal.", "Confirm delivery/contact details shown by portal.", "Pay official fee if required.", "Save acknowledgement/receipt."),
        workflow=("Submit reprint request.", "Complete payment/verification.", "PAN card/e-PAN dispatch or download is processed as per portal.", "Track using acknowledgement/reference."),
        status_tracking="Track with acknowledgement/reference on official PAN portal.",
        common_errors=("Wrong PAN/contact details. Resolution: verify details before OTP/payment.", "Reprint not allowed. Resolution: use correction/change flow if data needs update.", "Payment pending. Resolution: check official receipt/status before retry."),
        comparison=("PAN Reprint is for an existing PAN card copy when details do not need correction.", "PAN Correction is for changing PAN data such as name, DOB, address, or other supported details.", "Use correction first if PAN data is wrong; use reprint when PAN data is already correct."),
        official_tracking_url="https://www.protean-tinpan.com/services/pan/pan-index.html",
    ),
    _record(
        key="fssai_registration",
        service_name="FSSAI Basic Registration",
        category="Food Licensing",
        intent_keywords=("fssai registration", "basic registration", "food license", "basic food registration", "food registration", "एफएसएसएआई रजिस्ट्रेशन", "फूड लाइसेंस"),
        purpose="Help food business operators start FSSAI basic registration through the official FoSCoS portal.",
        official_url="https://foscos.fssai.gov.in/",
        who_can_use="Food Business Operator or authorized representative where basic registration applies.",
        eligibility="Eligibility depends on food business type, turnover/category, location, and FoSCoS rules.",
        prerequisites=("Business/FBO details.", "Kind of Business selection.", "Premises/address details.", "PAN/contact details if FoSCoS asks."),
        documents=("Documents shown by FoSCoS for the selected Kind of Business.", "Identity/address/business proof if required.", "Photo/declaration or premises document if required."),
        dsp_navigation=("Login to DSP if FSSAI service is enabled, or open FoSCoS.", "Select registration/new application.", "Choose state and Kind of Business.", "Continue only on FoSCoS pages."),
        form_filling=("Select Basic Registration if eligible as per FoSCoS.", "Fill FBO/business name, address, contact, and premises details.", "Select correct Kind of Business.", "Upload required documents.", "Pay official fee and save reference."),
        validation_rules=("Kind of Business must match actual activity.", "PAN/business details must match documents.", "Payment only through FoSCoS."),
        workflow=("Fill application.", "Upload documents.", "Pay official fee.", "Submit and save reference.", "Authority processes registration."),
        status_tracking="Use FoSCoS track/status option with application/reference number.",
        common_errors=("Wrong license type. Resolution: verify basic/state/central eligibility in FoSCoS.", "Missing KoB document. Resolution: check Documents Required section.", "Unofficial payment link. Resolution: pay only through FoSCoS."),
        official_helpdesk="helpdesk-foscos@fssai.gov.in / 1800-11-2100",
        official_tracking_url="https://foscos.fssai.gov.in/",
    ),
    _record(
        key="fssai_state_license",
        service_name="FSSAI State License",
        category="Food Licensing",
        intent_keywords=("fssai state license", "state food license", "food state license", "state license"),
        purpose="Help FBOs apply for FSSAI State License through FoSCoS when the business falls under state license category.",
        official_url="https://foscos.fssai.gov.in/",
        who_can_use="Food Business Operator or authorized representative as per FoSCoS state license rules.",
        eligibility="Turnover/category/KoB and premises rules must be checked on FoSCoS for the selected business.",
        prerequisites=("Business constitution and premises details.", "Kind of Business and production/activity details.", "Documents listed by FoSCoS for state license."),
        documents=("Documents required by FoSCoS for selected KoB/state license.", "Business identity/address/premises proof if asked.", "Food safety or technical documents if FoSCoS asks."),
        dsp_navigation=("Open FoSCoS through DSP if enabled or directly.", "Select New License/State License flow.", "Choose state and Kind of Business.", "Review document/fee requirements."),
        form_filling=("Select State License only if FoSCoS category applies.", "Fill FBO, premises, contact, product/activity, and KoB details.", "Upload state license documents.", "Pay fee on FoSCoS and submit.", "Save application/reference number."),
        workflow=("Submit state license application.", "Authority scrutiny/inspection if applicable.", "Approval or clarification/rejection.", "Download license when issued."),
        status_tracking="Track in FoSCoS using application/reference number.",
        approval_process="Approval depends on FSSAI/State authority scrutiny, document check, and inspection if applicable.",
        common_errors=("Basic vs State mismatch. Resolution: select license type as per FoSCoS eligibility.", "Document clarification. Resolution: respond through FoSCoS with requested documents.", "KoB mismatch. Resolution: choose actual food business activity."),
        official_helpdesk="helpdesk-foscos@fssai.gov.in / 1800-11-2100",
        official_tracking_url="https://foscos.fssai.gov.in/",
    ),
    _record(
        key="fssai_central_license",
        service_name="FSSAI Central License",
        category="Food Licensing",
        intent_keywords=("fssai central license", "central food license", "food central license", "central license"),
        purpose="Help FBOs apply for FSSAI Central License through FoSCoS where central license category applies.",
        official_url="https://foscos.fssai.gov.in/",
        who_can_use="Food Business Operator or authorized representative as per FoSCoS central license rules.",
        eligibility="Central license eligibility depends on turnover, business scale, import/export, product/activity, and FoSCoS rules.",
        prerequisites=("Business and premises details.", "KoB/product/activity details.", "Central license documents listed by FoSCoS."),
        documents=("Documents required by FoSCoS for central license and selected KoB.", "Business constitution/premises/technical documents if required.", "Product/import/export or other documents if FoSCoS asks."),
        dsp_navigation=("Open FoSCoS through DSP if enabled or directly.", "Select New License/Central License flow.", "Choose state, central category, and Kind of Business.", "Review official document and fee requirements."),
        form_filling=("Select Central License only if official category applies.", "Fill FBO, premises, product/activity, technical, and contact details.", "Upload required central license documents.", "Pay official fee and submit.", "Save reference for tracking."),
        workflow=("Submit central license application.", "Authority scrutiny/inspection/clarification if applicable.", "Approval/rejection as per FSSAI workflow.", "Download license when issued."),
        status_tracking="Track in FoSCoS using application/reference number.",
        approval_process="Approval depends on FSSAI authority scrutiny, document check, and inspection/clarification where applicable.",
        common_errors=("Wrong license category. Resolution: verify central license applicability in FoSCoS.", "Technical document missing. Resolution: use FoSCoS Documents Required list.", "Payment outside FoSCoS. Resolution: use official portal only."),
        official_helpdesk="helpdesk-foscos@fssai.gov.in / 1800-11-2100",
        official_tracking_url="https://foscos.fssai.gov.in/",
    ),
    _record(
        key="banking_correspondent",
        service_name="Banking Correspondent / Bank Mitra Services",
        category="Banking",
        intent_keywords=("banking correspondent", "bank mitra", "account opening", "banking service", "bc service", "csc bank mitra", "बैंक मित्र"),
        purpose="Help authorized CSC banking correspondents provide bank-linked services through official CSC/bank channels.",
        official_url="https://cscbankmitra.in/",
        who_can_use="Authorized VLE/BC/BF role and citizens using bank services through the official channel.",
        eligibility="VLE/BC access depends on CSC, bank, compliance, and role authorization.",
        prerequisites=("Authorized BC/BF credentials.", "Bank compliance/KYC process.", "Device/biometric/payment setup where required.", "Citizen consent."),
        documents=("Customer KYC documents if official bank flow asks.", "VLE/BC compliance documents if onboarding is required.", "Bank forms/consents as shown by bank portal."),
        dsp_navigation=("Login to Digital Seva/Bank Mitra portal if authorized.", "Select banking service such as account opening, deposit, withdrawal, enquiry, or request service.", "Continue only on official bank/CSC banking screen.", "Complete KYC/biometric/OTP as required by bank workflow."),
        form_filling=("Select exact banking service.", "Fill customer details only inside official bank portal fields.", "Verify KYC and consent.", "Complete biometric/OTP/device flow only on official screen.", "Save receipt/reference."),
        workflow=("Start service request.", "Complete KYC/transaction/verification.", "Submit to bank system.", "Provide receipt/acknowledgement.", "Track or reconcile as per bank portal."),
        status_tracking="Use official bank/CSC banking transaction history, receipt, or application reference.",
        approval_process="Account opening or BC service approval depends on bank KYC/compliance workflow.",
        common_errors=("KYC mismatch. Resolution: verify original documents.", "Device/biometric failed. Resolution: check RD/device setup.", "Transaction pending. Resolution: check official transaction status before retry."),
        important_notes=("Do not store customer bank, Aadhaar, OTP, or biometric data outside official workflow.",),
    ),
    _record(
        key="pmfby",
        service_name="Pradhan Mantri Fasal Bima Yojana (PMFBY)",
        category="Insurance",
        intent_keywords=("pmfby", "fasal bima", "crop insurance", "pradhan mantri fasal bima", "फसल बीमा"),
        purpose="PMFBY provides crop insurance service workflow through official crop insurance channels.",
        official_url="https://pmfby.gov.in/",
        who_can_use="Farmers/applicants assisted through authorized CSC/official crop insurance channel where enabled.",
        eligibility="Eligibility, notified crops, season, cut-off dates, and premium details must be checked on official PMFBY/state/insurance workflow.",
        prerequisites=("Farmer consent.", "Season/crop/state/district details.", "Land/crop/bank details as required by official portal.", "Payment method if premium is shown."),
        documents=("Identity/farmer details.", "Land/crop sowing details if required.", "Bank account details if official form asks.", "Other documents shown by official PMFBY flow."),
        dsp_navigation=("Login to DSP/insurance service if PMFBY is enabled, or open official PMFBY portal.", "Select crop insurance/PMFBY service.", "Choose state, season, crop, district, and farmer details as shown.", "Submit only before official cut-off and through official portal."),
        form_filling=("Select state/season/crop exactly.", "Fill farmer, land, bank, and crop details as per records.", "Check premium/sum insured and declarations shown by portal.", "Upload required documents if asked.", "Pay premium through official channel and save receipt/policy/reference."),
        workflow=("Create application.", "Verify crop/land/farmer details.", "Pay premium if applicable.", "Policy/application is processed.", "Claims/status follow official PMFBY workflow."),
        status_tracking="Track application/policy/claim status on official PMFBY or insurance portal using reference/policy details.",
        common_errors=("Wrong season/crop selected. Resolution: verify before submit.", "Cut-off date passed. Resolution: follow official PMFBY/state instructions.", "Claim/status pending. Resolution: track on PMFBY official status flow."),
        official_tracking_url="https://pmfby.gov.in/",
    ),
    _record(
        key="life_insurance",
        service_name="Life Insurance through CSC",
        category="Insurance",
        intent_keywords=("life insurance", "insurance registration", "insurance policy", "premium process", "जीवन बीमा"),
        purpose="Help citizens apply for life insurance products available through authorized CSC/insurance service channels.",
        official_url="https://insurance.csccloud.in/",
        who_can_use="Eligible citizen/proposer and authorized CSC/VLE/insurance role.",
        eligibility="Eligibility, premium, sum assured, age limits, and product terms depend on the selected official insurer/product.",
        prerequisites=("Customer consent.", "Product and coverage details explained.", "Nominee and payment details ready if official form asks."),
        documents=("Identity and address proof if required.", "Age/DOB proof if required.", "Nominee details.", "Bank/payment details only inside official portal if required."),
        dsp_navigation=("Login to DSP/CSC insurance portal if authorized.", "Select Life Insurance or exact insurer/product.", "Read product terms, premium, exclusions, and declaration.", "Fill only through official insurance screen."),
        form_filling=("Select product and plan carefully.", "Fill proposer/life insured details as per documents.", "Fill nominee, address, contact, premium/payment details on official portal.", "Explain declaration and consent before submit.", "Save proposal/policy/receipt number."),
        workflow=("Create proposal.", "Complete payment/KYC/declaration.", "Insurer processes proposal.", "Policy issued or clarification/rejection as per insurer workflow."),
        status_tracking="Track with proposal/policy/reference number in CSC insurance/insurer portal.",
        approval_process="Issuance depends on insurer underwriting and official product rules.",
        common_errors=("Wrong nominee/details. Resolution: review before submit.", "Premium payment pending. Resolution: check official receipt/status.", "Policy not issued. Resolution: track proposal and follow insurer clarification."),
    ),
    _record(
        key="jeevan_pramaan",
        service_name="Jeevan Pramaan / Digital Life Certificate",
        category="Pension",
        intent_keywords=("jeevan pramaan", "life certificate", "digital life certificate", "pension certificate", "जीवन प्रमाण", "लाइफ सर्टिफिकेट"),
        purpose="Jeevan Pramaan lets eligible pensioners generate a biometric Aadhaar-based Digital Life Certificate through CSC, PDA office, or official app.",
        official_url="https://jeevanpramaan.gov.in/v1.0/",
        who_can_use="Pensioners whose Pension Sanctioning Authority is onboarded on Jeevan Pramaan.",
        eligibility="Pensioner eligibility depends on onboarded Pension Sanctioning Authority and Jeevan Pramaan rules. Re-employed or re-married pensioner eligibility must be checked in official FAQ/rules.",
        prerequisites=("Pensioner consent.", "Biometric device/RD service if using CSC/PC/mobile flow.", "Internet connection.", "Pension-related details."),
        documents=("Aadhaar number/details only inside official Jeevan Pramaan flow.", "PPO number.", "Pension account/bank details.", "Pension Sanctioning and Disbursing Authority details.", "Mobile number."),
        dsp_navigation=("Open Jeevan Pramaan service through CSC/DSP if enabled or official Jeevan Pramaan application/portal.", "Enter pensioner details in official application.", "Capture fingerprint/iris biometric.", "Submit for Aadhaar-based authentication.", "Save generated Pramaan ID."),
        form_filling=("Fill pensioner name, mobile, PPO, bank/account, PSA/PDA details as required.", "Capture biometric only with pensioner consent.", "Verify all pension details before authentication.", "Submit and note Pramaan ID after success."),
        validation_rules=("Incorrect pension information may lead to rejection by authorities.", "Biometric/RD service must be working.", "Aadhaar/biometric data must be used only inside official application."),
        workflow=("Pensioner visits CSC/PDA or uses official app.", "Operator enters required pension details.", "Pensioner gives biometric authentication.", "Digital Life Certificate is generated with Pramaan ID.", "DLC is available to Pension Disbursing Agency online."),
        status_tracking="Use Pramaan ID and official Jeevan Pramaan options/PDA process.",
        download_print="Download/print certificate if official Jeevan Pramaan portal/app provides the option.",
        common_errors=("Biometric failed. Resolution: clean sensor, check RD service, retry with consent.", "Wrong PPO/bank/authority details. Resolution: verify pension documents before submit.", "Certificate rejected. Resolution: contact PDA/PSA with correct details."),
        official_tracking_url="https://jeevanpramaan.gov.in/v1.0/",
        faq=("Where can it be generated? At CSC centres, PDA offices, or official app where available.", "What is Pramaan ID? The unique ID generated after successful Digital Life Certificate creation."),
    ),
    _record(
        key="nps",
        service_name="National Pension System (NPS)",
        category="Pension",
        intent_keywords=("nps", "national pension system", "national pension scheme", "pension system", "एनपीएस"),
        purpose="NPS is a voluntary, portable, market-linked retirement savings system regulated/administered under official NPS/PFRDA framework.",
        official_url="https://npstrust.org.in/",
        who_can_use="Eligible Indian citizens/subscribers as per NPS rules and selected model/channel.",
        eligibility="Eligibility and subscriber type depend on official NPS rules, sector/model, and eNPS/PoP/channel requirements.",
        prerequisites=("Subscriber consent.", "KYC and contribution details ready.", "Official NPS/eNPS/PoP channel access."),
        documents=("KYC identity/address details as requested.", "PAN/bank/mobile/email only inside official channel.", "Nominee details.", "Contribution/payment details."),
        dsp_navigation=("Open NPS service through CSC/DSP if enabled, or official NPS/eNPS channel.", "Select registration/contribution/service request.", "Fill subscriber/KYC details only on official screen.", "Submit and save PRAN/reference."),
        form_filling=("Select correct subscriber type/service.", "Fill personal, KYC, nominee, and contact details as per documents.", "Choose pension fund/investment options only after explaining official options.", "Make contribution/payment on official channel.", "Save PRAN/receipt/reference."),
        workflow=("Register or login.", "Complete KYC and nominee details.", "Make contribution/payment if required.", "PRAN/account/service request is processed.", "Track through official NPS/eNPS channel."),
        status_tracking="Use PRAN/reference/receipt on official NPS/eNPS/CRA channel.",
        common_errors=("KYC mismatch. Resolution: correct details as per documents.", "Payment pending. Resolution: check official receipt before retry.", "Wrong subscriber type. Resolution: verify model/channel before submit."),
        official_tracking_url="https://enps.nps-proteantech.in/",
    ),
    _certificate_record("income_certificate", "Income Certificate", ("income certificate", "आय प्रमाण पत्र"), "income/family income", ("Identity proof.", "Address proof.", "Income proof or self-declaration as per state rules.", "Photo if required.")),
    _certificate_record("caste_certificate", "Caste Certificate", ("caste certificate", "जाति प्रमाण पत्र"), "caste/community", ("Identity proof.", "Address proof.", "Caste/community proof or family record as per state rules.", "Photo if required.")),
    _certificate_record("domicile_certificate", "Domicile Certificate", ("domicile certificate", "residence certificate", "निवास प्रमाण पत्र"), "residence/domicile", ("Identity proof.", "Address/residence proof.", "Previous residence/local authority documents if required.", "Photo if required.")),
    _certificate_record("birth_certificate", "Birth Certificate", ("birth certificate", "birth application", "जन्म प्रमाण पत्र"), "birth event", ("Parent/applicant identity proof.", "Hospital/birth record if required.", "Address proof.", "Relationship proof if required.")),
    _certificate_record("death_certificate", "Death Certificate", ("death certificate", "death application", "मृत्यु प्रमाण पत्र"), "death event", ("Applicant identity proof.", "Medical/hospital/death record if required.", "Address proof.", "Relationship proof if required.")),
    _record(
        key="eshram",
        service_name="e-Shram Registration",
        category="Employment & Welfare",
        intent_keywords=("e-shram", "eshram", "shram card", "labour card", "u-wins", "ई-श्रम", "श्रम कार्ड"),
        purpose="e-Shram is the official portal for registration/update of unorganised worker profile and e-Shram card services.",
        official_url="https://eshram.gov.in/indexmain",
        who_can_use="Unorganised workers/citizens as per official e-Shram rules, assisted by CSC where available.",
        eligibility="Eligibility and benefits must be verified on the official e-Shram portal.",
        prerequisites=("Worker consent.", "Mobile/OTP or authentication as required.", "Work/occupation and address details ready."),
        documents=("Identity details only inside official portal.", "Mobile number.", "Bank and occupation details if official form asks.", "Other documents shown by e-Shram portal."),
        dsp_navigation=("Login to DSP if e-Shram service is enabled, or open official e-Shram portal.", "Select Register on eShram or Update option.", "Complete authentication only on official portal.", "Fill worker profile and save card/reference."),
        form_filling=("Select registration/update.", "Fill worker name, address, occupation, education/skill, bank/contact details as required.", "Complete OTP/eKYC only on official portal.", "Review profile before submit.", "Download/print e-Shram card if generated."),
        workflow=("Authenticate worker.", "Fill worker profile.", "Submit registration/update.", "Generate/download e-Shram card.", "Update profile later if needed."),
        status_tracking="Use e-Shram login/update/profile options on official portal.",
        download_print="Download/print e-Shram card from official portal after successful registration.",
        common_errors=("OTP/authentication failed. Resolution: retry on official portal.", "Profile update needed. Resolution: use Update option after authentication.", "Service unavailable. Resolution: use official helpdesk/status."),
        official_helpdesk="14434 / 18008896811",
        official_tracking_url="https://eshram.gov.in/indexmain",
    ),
    _record(
        key="pmay",
        service_name="Pradhan Mantri Awas Yojana (PMAY)",
        category="Employment & Welfare",
        intent_keywords=("pmay", "awas yojana", "pradhan mantri awas", "pm awas", "आवास योजना", "प्रधानमंत्री आवास"),
        purpose="PMAY helps eligible citizens access affordable housing assistance through official Urban/Gramin PMAY channels.",
        official_url="https://pmay-urban.gov.in/",
        who_can_use="Eligible urban or rural applicants as per PMAY-U/PMAY-G rules.",
        eligibility="Eligibility depends on PMAY component, urban/rural category, beneficiary rules, and official portal verification.",
        prerequisites=("Applicant consent.", "Correct urban/rural component.", "Household, address, income/category, and bank details if portal asks."),
        documents=("Identity/address proof.", "Income/category/household proof if required.", "Bank details if required.", "Land/property documents if applicable."),
        dsp_navigation=("Login to DSP if PMAY service is enabled, or open official PMAY Urban/Gramin portal.", "Select apply/search/status option for correct PMAY component.", "Fill applicant/beneficiary details only on official portal.", "Save application/reference."),
        form_filling=("Choose PMAY-U or PMAY-G correctly.", "Fill applicant and family/household details as per documents.", "Enter address, income/category, bank/property details only if official form asks.", "Upload required proof.", "Submit and save reference."),
        workflow=("Apply/search beneficiary.", "Local/official verification.", "Approval/benefit processing as per PMAY workflow.", "Track status or beneficiary list."),
        status_tracking="Use official PMAY portal/MIS/status or beneficiary list options.",
        approval_process="Approval depends on official PMAY eligibility verification and local authority process.",
        common_errors=("Urban/Gramin component mismatch. Resolution: select the correct PMAY portal.", "Beneficiary not found. Resolution: recheck official details.", "Verification pending. Resolution: track on official PMAY portal/local authority."),
        official_tracking_url="https://pmaymis.gov.in/",
    ),
    _record(
        key="labour_registration",
        service_name="Labour Registration",
        category="Employment & Welfare",
        intent_keywords=("labour registration", "labor registration", "worker registration", "labour card", "श्रमिक रजिस्ट्रेशन", "लेबर कार्ड"),
        purpose="Help workers apply for labour/worker registration through enabled CSC/state labour or official government service portals.",
        official_url="https://services.india.gov.in/",
        who_can_use="Workers/applicants eligible under the relevant state/department labour welfare rules.",
        eligibility="Eligibility depends on the state labour department, worker category, age, occupation, and scheme rules.",
        prerequisites=("Worker consent.", "Correct state and worker category.", "Work/occupation details and documents ready."),
        documents=("Identity proof.", "Address proof.", "Age proof if required.", "Occupation/employment proof if required.", "Bank details if official form asks."),
        dsp_navigation=("Login to DSP if labour service is enabled, or open official state labour service.", "Select labour/worker registration.", "Choose state/category/scheme.", "Continue only on official portal."),
        form_filling=("Fill worker name, address, mobile, occupation, employer/work details as required.", "Enter bank/ID details only on official form if asked.", "Upload required proof.", "Submit and save acknowledgement."),
        workflow=("Fill registration.", "Upload documents.", "Submit/pay fee if applicable.", "Department verifies.", "Card/certificate/status is issued if approved."),
        status_tracking="Track with acknowledgement/reference number on official state labour/service portal.",
        common_errors=COMMON_DSP_ERROR_ITEMS + ("Wrong worker category. Resolution: verify scheme/category before submit.",),
        official_tracking_url="https://services.india.gov.in/",
    ),
    _record(
        key="scholarship_services",
        service_name="Scholarship Services",
        category="Employment & Welfare",
        intent_keywords=("scholarship", "student scholarship", "nsp scholarship", "छात्रवृत्ति"),
        purpose="Help students apply for scholarship services through official scholarship/Digital Seva/state portals where enabled.",
        official_url="https://scholarships.gov.in/",
        who_can_use="Eligible students/guardians as per the selected scholarship scheme.",
        eligibility="Eligibility depends on scholarship scheme, class/course, institution, category, income, and official rules.",
        prerequisites=("Student/guardian consent.", "Scheme and academic year selection.", "Institution, bank, income/category documents ready."),
        documents=("Student identity/details.", "Institution/course proof.", "Income certificate if required.", "Category certificate if required.", "Bank details if official form asks.", "Marksheets/photo if required."),
        dsp_navigation=("Login to DSP if scholarship service is enabled, or open official scholarship portal.", "Select new/renewal application and scheme.", "Fill student/institution/bank details only on official portal.", "Submit and save application ID."),
        form_filling=("Select correct scholarship scheme and year.", "Fill student, guardian, institution, course, class, and marks details.", "Upload required certificates/documents.", "Review bank/account details on official portal before submit.", "Save application ID."),
        workflow=("Register/login.", "Fill application.", "Upload documents.", "Institute/department verifies.", "Application is approved/rejected and payment processed as per scheme."),
        status_tracking="Use application ID/login on official scholarship portal.",
        approval_process="Approval depends on institute and department verification.",
        common_errors=("Wrong scheme selected. Resolution: verify eligibility before apply.", "Document mismatch. Resolution: upload scheme-required certificate.", "Bank validation failed. Resolution: correct bank details only on official portal."),
        official_tracking_url="https://scholarships.gov.in/",
    ),
    _record(
        key="flight_booking",
        service_name="Flight Booking through CSC Safar",
        category="Travel",
        intent_keywords=("flight booking", "flight ticket", "air ticket", "फ्लाइट टिकट"),
        purpose="Help VLE/citizen book flight tickets through authorized CSC travel service.",
        official_url="https://cscsafar.in/",
        who_can_use="Citizen/passenger assisted by authorized CSC/VLE travel service role.",
        prerequisites=("Passenger consent.", "Journey date, route, passenger details.", "Valid ID details only inside official booking page if required."),
        documents=("Passenger name/age/gender/contact.", "ID details if official booking portal asks.", "Payment method."),
        dsp_navigation=("Login to DSP/CSC Safar if authorized.", "Select Flight Tickets/Flight Booking.", "Search route/date/passengers.", "Review fare and rules before payment."),
        form_filling=("Enter from/to airports, date, passengers, class.", "Select flight after checking fare/timing/baggage/refund rules.", "Fill passenger details exactly as ID.", "Pay only on official travel/payment page.", "Save ticket/PNR/receipt."),
        workflow=("Search flight.", "Select itinerary.", "Fill passengers.", "Pay.", "Download ticket/PNR."),
        status_tracking="Track using PNR/booking ID on CSC Safar/airline official channel.",
        download_print="Print/download ticket and receipt after successful booking.",
        common_errors=("Wrong date/route selected. Resolution: review before payment.", "Payment pending. Resolution: check booking status before retry.", "Name mismatch. Resolution: enter passenger name exactly as ID."),
    ),
    _record(
        key="bus_booking",
        service_name="Bus Booking through CSC Safar",
        category="Travel",
        intent_keywords=("bus booking", "bus ticket", "बस टिकट"),
        purpose="Help citizens book bus tickets through authorized CSC travel service.",
        official_url="https://cscsafar.in/",
        who_can_use="Citizen/passenger assisted by authorized CSC/VLE travel service role.",
        prerequisites=("Passenger consent.", "Journey route/date/seat preference.", "Payment method."),
        documents=("Passenger details.", "Mobile/contact.", "ID details if official booking page asks."),
        dsp_navigation=("Login to DSP/CSC Safar if authorized.", "Select Bus Ticket/Bus Booking.", "Search route/date.", "Select bus/seat/fare and review rules."),
        form_filling=("Enter source, destination, date, passenger count.", "Select bus and seat.", "Fill passenger details.", "Review cancellation rules and fare.", "Pay and save ticket/PNR."),
        workflow=("Search bus.", "Select seat.", "Fill passenger details.", "Pay.", "Download ticket."),
        status_tracking="Track using booking ID/PNR in CSC Safar or operator channel.",
        download_print="Print/download ticket and receipt after booking.",
        common_errors=("Seat unavailable. Resolution: choose another seat/bus.", "Wrong passenger detail. Resolution: review before payment.", "Cancellation/refund issue. Resolution: follow official booking rules."),
    ),
    _record(
        key="darshan_booking",
        service_name="Darshan Booking through CSC Safar",
        category="Travel",
        intent_keywords=("darshan booking", "darshan", "temple booking", "दर्शन बुकिंग"),
        purpose="Help citizens book darshan/travel services available through authorized CSC Safar travel flow.",
        official_url="https://cscsafar.in/",
        who_can_use="Citizen/devotee/passenger assisted by authorized CSC/VLE where service is available.",
        prerequisites=("Citizen consent.", "Date/time/location and passenger/devotee details.", "ID/payment details only on official booking page if asked."),
        documents=("Name/contact details.", "ID details if official darshan/travel page asks.", "Payment method."),
        dsp_navigation=("Login to DSP/CSC Safar if authorized.", "Select Darshan Booking.", "Choose location/date/slot/service shown.", "Review booking rules before payment."),
        form_filling=("Select darshan/location and slot.", "Fill visitor/passenger details.", "Review date, timing, fee, and cancellation rules.", "Pay on official page.", "Save booking ID/receipt."),
        workflow=("Select darshan service.", "Fill visitor details.", "Pay if required.", "Download/print booking confirmation."),
        status_tracking="Track using booking/reference ID on official CSC Safar/service channel.",
        download_print="Print/download booking confirmation/receipt after successful booking.",
        common_errors=("Slot unavailable. Resolution: choose another slot/date.", "Wrong visitor detail. Resolution: review before payment.", "Payment pending. Resolution: check status before retry."),
    ),
    _record(
        key="pmgdisha",
        service_name="PMGDISHA",
        category="Education",
        intent_keywords=("pmgdisha", "digital literacy", "gramin digital saksharta", "पीएमजीदिशा", "डिजिटल साक्षरता"),
        purpose="PMGDISHA is a digital literacy scheme/service for rural citizens through authorized training/CSC channels.",
        official_url="https://www.pmgdisha.in/",
        who_can_use="Eligible learners/training centres/VLEs as per PMGDISHA official rules.",
        eligibility="Eligibility, enrolment rules, and certification process must be checked on official PMGDISHA portal.",
        prerequisites=("Learner consent.", "Learner details and training centre access.", "Assessment/certification flow as per PMGDISHA."),
        documents=("Learner identity/contact details as required.", "Photo or demographic details if portal asks.", "Training/centre details."),
        dsp_navigation=("Login to PMGDISHA/DSP flow if authorized.", "Select candidate enrolment/training/certification option.", "Fill learner details on official portal.", "Proceed with training and assessment as per portal."),
        form_filling=("Register/enrol learner.", "Fill name, age, gender, address, mobile, education/category fields as required.", "Do not share child/minor personal data in chat.", "Complete training/assessment workflow.", "Download/print certificate if generated."),
        workflow=("Enrol candidate.", "Provide digital literacy training.", "Complete assessment.", "Certification is generated as per PMGDISHA process."),
        status_tracking="Track candidate/enrolment/certificate status on PMGDISHA portal.",
        download_print="Download/print certificate from PMGDISHA when available.",
        common_errors=("Candidate details mismatch. Resolution: correct before assessment/certificate.", "Login/role issue. Resolution: check authorized account.", "Certificate not generated. Resolution: verify assessment/status."),
    ),
    _record(
        key="csc_academy",
        service_name="CSC Academy",
        category="Education",
        intent_keywords=("csc academy", "academy course", "csc training", "सीएससी अकादमी"),
        purpose="CSC Academy provides learning/training/certification services through official CSC Academy channels.",
        official_url="https://www.cscacademy.org/",
        who_can_use="Learners/VLEs/citizens as per selected CSC Academy course rules.",
        eligibility="Eligibility depends on the specific course/training/certification.",
        prerequisites=("Course selection.", "Learner consent.", "Required learner details and payment if course fee applies."),
        documents=("Learner identity/contact details if required.", "Education/qualification proof if course asks.", "Photo/certificate details if required."),
        dsp_navigation=("Open CSC Academy or DSP education service if enabled.", "Select course/training/certification.", "Read eligibility, fee, schedule, and certificate rules.", "Register/enrol only on official portal."),
        form_filling=("Select correct course.", "Fill learner details as per documents.", "Upload required proof if asked.", "Pay fee only on official portal if applicable.", "Save enrolment/reference."),
        workflow=("Register/enrol.", "Complete course/training.", "Take assessment if required.", "Certificate/record is issued as per course rules."),
        status_tracking="Track enrolment/course/certificate status on CSC Academy portal.",
        download_print="Download certificate/receipt from official portal when available.",
        common_errors=("Wrong course selected. Resolution: verify course before payment.", "Certificate pending. Resolution: check completion/assessment status.", "Payment pending. Resolution: verify official receipt."),
    ),
    _record(
        key="tally_course",
        service_name="Tally Course / Tally Certification",
        category="Education",
        intent_keywords=("tally course", "tally certification", "tally", "टैली कोर्स"),
        purpose="Help learners register for Tally or accounting-related course/certification available through CSC education/skill channels.",
        official_url="https://skill.csc-services.in/",
        who_can_use="Learners eligible for the selected Tally/course service.",
        eligibility="Eligibility, fee, batch, and certificate rules depend on the official course page.",
        prerequisites=("Learner consent.", "Course/batch selection.", "Education/contact details ready."),
        documents=("Learner identity/contact details.", "Education details if required.", "Photo/category proof if portal asks."),
        dsp_navigation=("Login to DSP/skill portal if enabled.", "Search Tally/Tally Certification/course service.", "Select course/batch.", "Continue on official skill/course screen."),
        form_filling=("Select Tally course/certification.", "Fill learner name, mobile/email, address, education, and centre/batch details.", "Upload required proof if asked.", "Pay fee if applicable.", "Save enrolment/receipt."),
        workflow=("Register learner.", "Complete course/training.", "Complete assessment/certification if applicable.", "Download certificate when available."),
        status_tracking="Track enrolment/certificate in the official skill/course portal.",
        common_errors=("Course not visible. Resolution: check role/availability.", "Wrong learner details. Resolution: correct before certificate generation.", "Certificate pending. Resolution: verify course completion/assessment."),
    ),
    _record(
        key="digital_unnati",
        service_name="Digital Unnati",
        category="Education",
        intent_keywords=("digital unnati", "digital unnati course", "डिजिटल उन्नति"),
        purpose="Help learners access Digital Unnati/skilling service where available through Digital Seva/skill channels.",
        official_url="https://skill.csc-services.in/",
        who_can_use="Learners/citizens as per the official Digital Unnati service rules.",
        eligibility="Eligibility, course content, fee, and certificate rules depend on the official service screen.",
        prerequisites=("Learner consent.", "Course/service selection.", "Basic learner/contact details ready."),
        documents=("Learner identity/contact details.", "Education/qualification details if required.", "Photo/proof if portal asks."),
        dsp_navigation=("Login to DSP/skill portal if service is enabled.", "Search Digital Unnati.", "Open the exact service/course.", "Read course, fee, certificate, and eligibility instructions."),
        form_filling=("Select Digital Unnati service/course.", "Fill learner details.", "Upload documents only if required.", "Submit/pay if applicable.", "Save enrolment/reference."),
        workflow=("Enrol learner.", "Complete training/course activity.", "Complete assessment if required.", "Download certificate/record if generated."),
        status_tracking="Track enrolment/course/certificate status in official skill/DSP service.",
        common_errors=("Service not enabled. Resolution: check DSP role/service availability.", "Learner details mismatch. Resolution: correct before final submit.", "Certificate not visible. Resolution: check training/assessment status."),
    ),
)


CORE_SERVICE_PROFILE_CONTEXTS = {
    record["key"]: _context(record)
    for record in CORE_SERVICE_RECORDS
}


_BROAD_SERVICE_KEYS = {"csc_overview"}

CORE_SERVICE_KEYWORDS = tuple(
    (record["key"], record["intent_keywords"])
    for record in CORE_SERVICE_RECORDS
    if record["key"] not in _BROAD_SERVICE_KEYS
) + tuple(
    (record["key"], record["intent_keywords"])
    for record in CORE_SERVICE_RECORDS
    if record["key"] in _BROAD_SERVICE_KEYS
)
